# version: '3.7'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    #   - prometheus
    #   - grafana

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_db
    volumes:
      - db_data:/var/lib/postgresql/data
    depends_on:
      - app
      
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  k6:
    image: grafana/k6
    volumes:
      - ./load_test:/scripts
    entrypoint: [""]  # Allows custom commands
    depends_on:
      - app

volumes:
  db_data:
